### ISSUE TITLE
Version 1.0.1 from Modrinth 1.16.x-1.17.1 release does not work on MC version 1.16.5

### ISSUE THREAD

**Issue by EltoCode** [pog5/mc-leashplayers#10]
<details>
  <summary>Console Logs</summary>
  
```
31.01 00:01:45 [Server] main/WARN Mod resolution failed
31.01 00:01:45 [Server] main/INFO Immediate reason: [HARD_DEP_NO_CANDIDATE leashmod 1.0.0 {depends fabric-api @ [*]}, ROOT_FORCELOAD_SINGLE leashmod 1.0.0]
31.01 00:01:45 [Server] main/INFO Reason: [HARD_DEP leashmod 1.0.0 {depends fabric-api @ [*]}, HARD_DEP leashmod 1.0.0 {depends minecraft @ [~1.19.3]}, HARD_DEP leashmod 1.0.0 {depends java @ [>=17]}]
31.01 00:01:45 [Server] main/INFO SERVER environment disabled: [fabric-renderer-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-textures-v0, fabric-models-v0, fabric-screen-api-v1, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
31.01 00:01:45 [Server] main/INFO Fix: add [], remove [], replace [[leashmod 1.0.0] -> add:leashmod 1 ([(-∞,∞)])]
31.01 00:01:45 [Server] main/ERROR Incompatible mods found!
31.01 00:01:45 [Server] INFO net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
31.01 00:01:45 [Server] INFO A potential solution has been determined, this may resolve your problem:
31.01 00:01:45 [Server] INFO - Replace mod 'Leashable Players' (leashmod) 1.0.0 with any version that is compatible with:
31.01 00:01:45 [Server] INFO - minecraft 1.16.5
31.01 00:01:45 [Server] INFO - java 11
31.01 00:01:45 [Server] INFO More details:
31.01 00:01:45 [Server] INFO - Mod 'Leashable Players' (leashmod) 1.0.0 requires any version of fabric-api, which is missing!
31.01 00:01:45 [Server] INFO - Mod 'Leashable Players' (leashmod) 1.0.0 requires any version between 1.19.3 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
31.01 00:01:45 [Server] INFO - Mod 'Leashable Players' (leashmod) 1.0.0 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 11!
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.2.jar:?]
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.2.jar:?]
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.2.jar:?]
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.2.jar:?]
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.2.jar:?]
31.01 00:01:45 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.2.jar:?]
31.01 00:01:47 [Multicraft] Server shut down (starting)
```
  
</details>

The latest version of fabric api for 1.16.5 is installed. Using `leashable-players-1.1,jar`. Some other mods are also installed. Origins is not installed.

**Comment by louarn-rous** [comment]
i ran into this issue as well. running v1.0.1 in 1.16.5 returns the following error:
```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Leashable Players' (leashmod) 1.0.0 with any version that is compatible with:
		 - minecraft 1.16.5
		 - java 8
More details:
	 - Mod 'Leashable Players' (leashmod) 1.0.0 requires any version of fabric-api, which is missing!
	 - Mod 'Leashable Players' (leashmod) 1.0.0 requires any version between 1.19.3 (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Leashable Players' (leashmod) 1.0.0 requires version 17 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
	
- it indicates the mod version as being 1.0.0, despite it being 1.0.1 (or 1.1? the package name isn't consistent)
- it does not detect fabric-api, even though it is not missing
- it demands a different game version
- it demands a different version of Java (which as far as i know shouldn't be a problem at all)

**Comment by pog5** [comment]
Aside from using a older version, I can't provide you for much support as supporting multiple versions is hard enough, and making those versions older makes it even harder as more and more changes pile up thanks to Mojang.
